import os
import sys
import requests
from io import BytesIO
from PIL import Image

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.database import SessionLocal
from backend.models import Cake

STATIC_DIR = os.path.join(os.path.dirname(__file__), "static", "images", "cakes")
os.makedirs(STATIC_DIR, exist_ok=True)

def optimize_image(source: str, output_path: str, is_local: bool = False):
    """Downloads or opens an image, resizes it if needed, and saves it as WebP."""
    try:
        if is_local:
            # Reconstruct local path from backend directory
            db_path = source.lstrip("/")
            local_path = os.path.join(os.path.dirname(__file__), db_path)
            img = Image.open(local_path)
        else:
            response = requests.get(source, timeout=15)
            response.raise_for_status()
            img = Image.open(BytesIO(response.content))
        
        # Convert to RGB (required for WebP compatibility if original is RGBA or P)
        if img.mode in ("RGBA", "P"):
            img = img.convert("RGB")
            
        # Max dimensions constraints
        max_size = (800, 800)
        img.thumbnail(max_size, Image.Resampling.LANCZOS)
        
        # Save as optimized webp
        img.save(output_path, "WEBP", quality=80, optimize=True)
        return True
    except Exception as e:
        print(f"Failed to optimize {source}: {e}")
        return False

def main():
    db = SessionLocal()
    cakes = db.query(Cake).all()
    print(f"Starting image optimization for {len(cakes)} cakes...")
    
    optimized_count = 0
    
    for cake in cakes:
        if not cake.image_url:
            continue
            
        original_url = cake.image_url
        
        # Determine paths
        filename = f"{cake.id}.webp"
        filepath = os.path.join(STATIC_DIR, filename)
        new_relative_url = f"/static/images/cakes/{filename}"
        
        # Skip if already a webp generated by us
        if original_url == new_relative_url:
            continue

        print(f"Processing ID {cake.id}: {original_url}")
        is_local = original_url.startswith("/")
        success = optimize_image(original_url, filepath, is_local=is_local)
        
        if success:
            cake.image_url = new_relative_url
            optimized_count += 1
            print(f" -> Optimized and updated URL to {new_relative_url}")
        else:
            print(f" -> Failed to process {original_url}")

    db.commit()
    db.close()
    print(f"\nOptimization complete! Successfully processed {optimized_count} images.")

if __name__ == "__main__":
    main()
